### ISSUE TITLE
display file content

### ISSUE THREAD

**Issue by cheetahbyte** [cheetahbyte/molecule#4]

**Comment by cheetahbyte** [comment]
# Implement interactions with the file
Displaying, editing and saving the content should be implemented.
## ToDo
- [ ] Getting file content
- [ ] Editing file content
- [ ] Saving file content
